
steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--legacy-peer-deps']
# Build the Next.js application
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
options:
  logging: CLOUD_LOGGING_ONLY

